export const POST_CART_PRODUCTS_REQUEST = "POST_CART_PRODUCTS_REQUEST";
export const POST_CART_PRODUCTS_SUCCESS = "POST_CART_PRODUCTS_SUCCESS";
export const POST_CART_PRODUCTS_FAILURE = "POST_CART_PRODUCTS_FAILURE";



export const GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST";
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS";
export const GET_CART_PRODUCTS_FAILURE = "GET_CART_PRODUCTS_FAILURE";



export const DELETE_CART_PRODUCTS_REQUEST = "DELETE_CART_PRODUCTS_REQUEST";
export const DELETE_CART_PRODUCTS_SUCCESS = "DELETE_CART_PRODUCTS_SUCCESS";
export const DELETE_CART_PRODUCTS_FAILURE = "DELETE_CART_PRODUCTS_FAILURE";


export const CLEAR_CART_PRODUCTS_REQUEST = "CLEAR_CART_PRODUCTS_REQUEST";
export const CLEAR_CART_PRODUCTS_SUCCESS = "CLEAR_CART_PRODUCTS_SUCCESS";
export const CLEAR_CART_PRODUCTS_FAILURE = "CLEAR_CART_PRODUCTS_FAILURE";
